### ISSUE TITLE
'Finish editing' does not save changes when model calculations have not yet been completed

### ISSUE THREAD

**Issue by mabijkerk** [quintel/multi-year-charts#36]
When making changes to scenarios in the MYC, the model needs time to recalculate. If the button 'Finish editing' is clicked before the recalculation is done, then the changed values are not saved.

@noracato is this something you can look into? I would expect the updated input values to be passed to the scenario **before** the calculations are started, instead of **after**.

**Comment by thomas-qah** [comment]
Hi @mabijkerk and @noracato! I took some time to research this issue.

The reason the scenario's input values are not saved when the `Finish editing` button is clicked is because this closes the iframe that contains an entire instance of the ETM. When the iframe closes it also ends the request that is currently being processed by the ETM, even if it is in the middle of something such as calculations.

Some possible solutions:
- Storing the input values first and the results of the calculations for the updated scenario is possible, but it would complicate things quite a bit.
  - We could for example add boolean flags to the scenario that indicate what has been and should still be done, such as `has_dirty_input_values` (`dirty` is what Rails calls edited but unpersisted attributes) and/or `needs_recalculation`.
  - We could create a copy of "unprocessed" scenarios and put them in a list somewhere.
- Another option could be to process scenario updates in a background queue, which would "detach" them from the iframe doing the request. The ETM instance could then poll the server to see if the scenario has been updated yet and "refresh" if needed.
- A third option could be to let the MYC app check if the iframe containing the ETM instance is currently performing requests, and if so, disable the `Finish editing` button.

Of these options the latter seems best but needs more research. I'll put a little more time into doing that.

**Comment by thomas-qah** [comment]
Some further research into option 3 above led me to the [postMessage browser API](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) that seems to make communication between iframes/popups and their parent windows possible. We could make the iframed ETM instance send out a message when it starts/stops updating a scenario. The parent popup could then listen to this and disable/enable its `Finish editing` button as required.

Let's discuss if this is the desired solution!

**Comment by thomas-qah** [comment]
> A third option could be to let the MYC app check if the iframe containing the ETM instance is currently performing requests, and if so, disable the Finish editing button.

This fix is now implemented through https://github.com/quintel/etmodel/pull/4140 and https://github.com/quintel/multi-year-charts/pull/41.
